# H2 Database Configuration (for development)
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:admin
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.h2.Driver

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Initialize database using data.sql
spring.sql.init.mode=always
spring.sql.init.platform=h2
